In [100]:
from ase import Atoms
from ase.visualize import view

In [101]:
d = 1.1
co = Atoms('CO2', positions=[(0, 0, 0), (0, d, 0), (d, 0, 0)])
view(co)

<Popen: returncode: None args: ['C:\\Users\\ASUS\\anaconda3\\python.exe', '-...>

In [3]:
from ase.cluster.cubic import FaceCenteredCubic

In [10]:
surfaces = [(1, 1, 1), (1, 1, 1), (1, 1, 1)]
layers = [10, 10, 10]
lc = 3.61000
atoms = FaceCenteredCubic('Cu', surfaces, layers, latticeconstant=lc)
view(atoms)

<Popen: returncode: None args: ['C:\\Users\\ASUS\\anaconda3\\python.exe', '-...>

In [39]:
import numpy as np

In [40]:
surfaces = [(1, 0, 0), (1, 1, 0), (1, 1, 1)]
layers = [50, 50, 50]
lc = 3.61000
atomsCu = FaceCenteredCubic('Cu', surfaces, layers, latticeconstant=lc)

possCu = atomsCu.get_positions()
cCu = atomsCu.get_center_of_mass()

new_possCu = possCu - cCu

In [41]:
def cut_atoms(poss, r):
    radii = np.linalg.norm(poss, axis=1)  
    return poss[radii < r]

In [42]:
r1 = 5
possCu = cut_atoms(new_possCu, r1)
atoms = Atoms('Cu'+str(len(possCu)), positions=possCu)
view(atoms)

<Popen: returncode: None args: ['C:\\Users\\ASUS\\anaconda3\\python.exe', '-...>

In [49]:
def cut_atoms_inside(poss, r):
    radii = np.linalg.norm(poss, axis=1)  
    return poss[radii > r]

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[2, 3, 4], [5, 6, 7]])
print(np.vstack([a, b]))

[[1 2 3]
 [4 5 6]
 [2 3 4]
 [5 6 7]]


In [102]:
lc_ag = 4.09
lc_cu = 3.61
atomsAg = FaceCenteredCubic('Ag', surfaces, layers, latticeconstant=lc_ag)
atomsCu = FaceCenteredCubic('Cu', surfaces, layers, latticeconstant=lc_cu)

pos_Cu = atomsCu.get_positions()
pos_Ag = atomsAg.get_positions()
cCu = atomsCu.get_center_of_mass()
cAg = atomsAg.get_center_of_mass()
pos_Cu -= cCu
pos_Ag -=cAg

r1 = 5
r2 = 7

new_pos_Ag = cut_atoms_inside(cut_atoms(pos_Ag, r2), r1)
new_pos_Cu = cut_atoms(pos_Cu, r1)
new_pos = np.vstack([new_pos_Ag, new_pos_Cu])

symbols = ['Ag'] * len(new_pos_Ag) + ['Cu'] * len(new_pos_Cu)
atoms_CuAg = Atoms(symbols, new_pos)
view(atoms_CuAg)


<Popen: returncode: None args: ['C:\\Users\\ASUS\\anaconda3\\python.exe', '-...>

In [103]:
from ase.calculators.emt import EMT
atoms_CuAg.calc = EMT()

In [104]:
energy = atoms_CuAg.get_potential_energy()
print(f"Energy: {energy:.2f} eV")
view(atoms_CuAg)

Energy: 8839.92 eV


<Popen: returncode: None args: ['C:\\Users\\ASUS\\anaconda3\\python.exe', '-...>

In [105]:
from ase.optimize import BFGS

In [106]:
optimizer = BFGS(atoms_CuAg)
optimizer.run(fmax=0.02) 

      Step     Time          Energy          fmax
BFGS:    0 15:35:25     8839.922783     1098.458812
BFGS:    1 15:35:25     2581.560603      345.736570
BFGS:    2 15:35:25     1417.543380      196.806354
BFGS:    3 15:35:25      600.635592       85.824663
BFGS:    4 15:35:25      327.239012       39.592571
BFGS:    5 15:35:25      239.751982       21.155007
BFGS:    6 15:35:25      184.741077       13.901835
BFGS:    7 15:35:25      149.637413       10.180349
BFGS:    8 15:35:25      113.188307        7.494397
BFGS:    9 15:35:25       87.869133        5.291680
BFGS:   10 15:35:25       70.802088        3.440669
BFGS:   11 15:35:25       60.431189        2.070684
BFGS:   12 15:35:26       55.425227        1.367070
BFGS:   13 15:35:26       54.512018        1.065408
BFGS:   14 15:35:26       54.230876        0.923632
BFGS:   15 15:35:26       53.867212        0.740010
BFGS:   16 15:35:26       53.479653        0.504540
BFGS:   17 15:35:26       53.281276        0.547301
BFGS:   18 15:

True

In [107]:
view(atoms_CuAg)

<Popen: returncode: None args: ['C:\\Users\\ASUS\\anaconda3\\python.exe', '-...>

In [108]:
energy = atoms_CuAg.get_potential_energy()
print(f"Energy: {energy:.2f} eV")
view(atoms_CuAg)

Energy: 31.42 eV


<Popen: returncode: None args: ['C:\\Users\\ASUS\\anaconda3\\python.exe', '-...>